// swift-tools-version: 5.10
// This file is GENERATED by fresco-pantry-ios/scripts/render-manifest.sh. Do not edit it by hand —
// the version and the checksum must always describe the same artifact, so they are written together
// or not at all.
//
// A deliberately low tools version: a partner on an older Xcode can still resolve this package, and
// nothing here needs a newer manifest API. The iOS floor is the Pantry framework's, not this file's.
import PackageDescription

let package = Package(
  name: "fresco-pantry-swift",
  platforms: [.iOS("16.4")],
  products: [
    .library(name: "Pantry", targets: ["Pantry"])
  ],
  targets: [
    .binaryTarget(
      name: "Pantry",
      url: "https://github.com/dropkitchen/fresco-pantry-swift/releases/download/v0.5.0/Pantry.xcframework.zip",
      checksum: "711a94020f8e1c03ea84ab018e0eac47bcc9ee420cc86b9b8c23d26667b49a02"
    )
  ]
)
